import Head from 'next/head'
import { useRouter } from 'next/router'
import nookies from 'nookies'
import { AppInputSearch, AppButton } from '../components'

export default function Index({ defaultLanguage }) {
  const { reload } = useRouter()

  const onChangeLanguage = (lang): void => {
    nookies.set(null, 'lang', lang, { path: '/' })
    if (lang !== defaultLanguage) {
      reload()
    }
  }

  return (
    <div style={{ backgroundColor: 'black' }}>
      <Head>
        <title>DoubleCard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppInputSearch placeholder={'testtt'} />
      <AppButton
        text="En francais"
        onClick={() => onChangeLanguage('fr')}
      ></AppButton>
      <AppButton
        text="En anglais"
        onClick={() => onChangeLanguage('en')}
      ></AppButton>
    </div>
  )
}
