import { Box } from '@chakra-ui/react'
import { AppButton, AppText } from 'components'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React, { useState } from 'react'
import { getLanguageHeaders } from 'utils'
import nookies from 'nookies'
import useSocket from 'hooks/useSocket'

export default function Index({ defaultLanguage }) {
  const t1 = useTranslation('common')
  const [message, setMessage] = useState()
  const socket = useSocket()

  const { reload } = useRouter()

  const onChangeLanguage = (lang): void => {
    nookies.set(null, 'lang', lang, { path: '/' })
    if (lang !== defaultLanguage) {
      reload()
    }
  }

  const sendMessage = (msg) => {
    socket.emit('message', { data: msg })
  }

  if (socket)
    socket.on('connexion', (data) => {
      console.log(data)
      setMessage(data)
      socket.emit('pseudo', { data: data })
    })

  return (
    <div style={{ backgroundColor: 'black' }}>
      <Head>
        <title>DoubleCard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <AppText>{t1.t('common:hello')}</AppText>
      </Box>

      <AppText>mon id:{message}</AppText>

      <AppButton
        text="En francais"
        onClick={() => onChangeLanguage('fr')}
      ></AppButton>
      <AppButton
        text="En anglais"
        onClick={() => onChangeLanguage('en')}
      ></AppButton>
      <AppButton
        text=" Voir mon message"
        onClick={() => sendMessage('my messageeee')}
      ></AppButton>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  return {
    props: {
      defaultLanguage: getLanguageHeaders(context),
      ...(await serverSideTranslations(getLanguageHeaders(context), [
        'common',
      ])),
    },
  }
}
